project:
  type: website
  output-dir: docs

website:
  title: "Clark Miyamoto's Homepage"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog/index.qmd
        text: Blog  # Add the blog link here, which will be part of the top navbar
  sidebar: []  # Remove the sidebar entirely, or just leave it empty

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
