project:
  type: website
  output-dir: docs

website:
  title: "<a href='index.qmd'>Clark Miyamoto's Homepage</a>"  # Title is now a clickable link to home
  navbar:
    left:
      - href: blog/index.qmd
        text: Blog  # Only the Blog link remains
  sidebar: []  # No sidebar

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
