project:
  type: website
  output-dir: docs
  resources:
    - external/begrohu2025/main.pdf
  

website:
  title: "<a href='/index.qmd'>Clark Miyamoto</a>"
  navbar:
    left:
      - href: blog/index.qmd
        text: Blog 
  sidebar: []  # No sidebar

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
